title: Applications of Language Models
description: This is the website for the course "Applications of Language Models" offered by IIIT Hyderabad.
theme: just-the-docs

url: 'https://applicationsoflanguagemodels.github.io/'

remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
  Vasudeva Varma:
    - 'https://irel.iiit.ac.in/vasu/bio.html'
  Moodle:
    - 'https://courses.iiit.ac.in'
footer_content: Copyright &copy; 2025 Manav Chaudhary. Distributed by an <a href="https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt">MIT license.</a>
